from classification.models.ConvNeXt_V2 import CustomizedConvNeXT_V2
from classification.models.EfficientNetV2 import CustomizedEfficientnetV2
from classification.models.MiniVGG import MiniVGG
from classification.models.ViT import CustomizedViT